### ISSUE TITLE
add navigation to dashboard

### ISSUE THREAD

**Issue by siddhantprateek** [siddhantprateek/Cryptocurrency-Tracker#4]

**Comment by doboianh** [comment]
Can i do it guy ?

**Comment by siddhantprateek** [comment]
> Can i do it guy ?

sure, go ahead

**Comment by doboianh** [comment]
Sure, i will complete it as soon as possible

**Comment by doboianh** [comment]
![image](https://user-images.githubusercontent.com/91415970/140597007-3476e6f8-ff00-4cb9-953a-1b708dbdb96f.png)
Is it ok ? Can i push source code to you ?

**Comment by siddhantprateek** [comment]
Yes, the navbar is good, but I would prefer to remove the dropdown button, add the logo at the left, and add the `dashboard` and `login` nav link to it(right).

**Comment by doboianh** [comment]
Hey guy, how about this ?
![image](https://user-images.githubusercontent.com/91415970/140602263-72bb6658-6e60-4715-b45f-b4a4cd1e2499.png)

**Comment by siddhantprateek** [comment]
LGTM, If you could change the font style to `Poppins`, It will match the UI design.

**Comment by doboianh** [comment]
> LGTM, If you could change the font style to `Poppins`, It will match the UI design.

Could you fix it ? i will share source code for you

**Comment by doboianh** [comment]
could you give me permission?

**Comment by siddhantprateek** [comment]
> > LGTM, If you could change the font style to `Poppins`, It will match the UI design.
> 
> Could you fix it ? i will share source code for you

Sharing won't be necessary. Create a PR, I'll review it. 
I'll create an issue for fixing the font style.

**Comment by doboianh** [comment]
> > > LGTM, If you could change the font style to `Poppins`, It will match the UI design.
> > 
> > 
> > Could you fix it ? i will share source code for you
> 
> Sharing won't be necessary. Create a PR, I'll review it. I'll create an issue for fixing the font style.

Hey guy, I can't create PR, 
![image](https://user-images.githubusercontent.com/91415970/140637201-7c464313-748e-45e1-9f45-b99b7dfb2a03.png)

**Comment by siddhantprateek** [comment]
Use this as a reference https://opensource.com/article/19/7/create-pull-request-github

**Comment by siddhantprateek** [comment]
sure

**Comment by doboianh** [comment]
> Use this as a reference https://opensource.com/article/19/7/create-pull-request-github

I created PR from my side., Can you support me ? This is my first time I used github
